Starting Container

2025-08-22 17:05:22.515 | DEBUG    | axiestudio.services.settings.base:set_database_url:361 - No database_url provided, trying AXIESTUDIO_DATABASE_URL env variable

2025-08-22 17:05:22.515 | DEBUG    | axiestudio.services.settings.base:set_database_url:364 - Using AXIESTUDIO_DATABASE_URL env variable.

2025-08-22 17:05:22.515 | DEBUG    | axiestudio.services.settings.base:set_components_path:460 - Setting default components path to components_path

2025-08-22 17:05:22.515 | DEBUG    | axiestudio.services.settings.base:set_components_path:468 - Components path: ['/app/.venv/lib/python3.12/site-packages/axiestudio/components']

2025-08-22 17:05:22.515 | DEBUG    | axiestudio.services.settings.base:set_user_agent:313 - Setting user agent to axiestudio

Traceback (most recent call last):

  File "/app/.venv/bin/axiestudio", line 10, in <module>

    sys.exit(main())

             ^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/axiestudio_launcher.py", line 18, in main

    from axiestudio.__main__ import main as axiestudio_main

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/__main__.py", line 31, in <module>

    from axiestudio.main import setup_app

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/main.py", line 26, in <module>

    from axiestudio.api import health_check_router, log_router, router

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/__init__.py", line 3, in <module>

    from axiestudio.api.router import router

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/router.py", line 4, in <module>

    from axiestudio.api.v1 import (

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/v1/__init__.py", line 4, in <module>

    from axiestudio.api.v1.email_verification import router as email_verification_router

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/v1/email_verification.py", line 8, in <module>

    from axiestudio.services.email.service import email_service

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/services/email/service.py", line 15, in <module>

    from axiestudio.services.settings.email import EmailSettings

ModuleNotFoundError: No module named 'axiestudio.services.settings.email'

2025-08-22 17:05:31.044 | DEBUG    | axiestudio.services.settings.base:set_database_url:361 - No database_url provided, trying AXIESTUDIO_DATABASE_URL env variable

2025-08-22 17:05:31.044 | DEBUG    | axiestudio.services.settings.base:set_database_url:364 - Using AXIESTUDIO_DATABASE_URL env variable.

2025-08-22 17:05:31.044 | DEBUG    | axiestudio.services.settings.base:set_components_path:460 - Setting default components path to components_path

2025-08-22 17:05:31.044 | DEBUG    | axiestudio.services.settings.base:set_components_path:468 - Components path: ['/app/.venv/lib/python3.12/site-packages/axiestudio/components']

2025-08-22 17:05:31.044 | DEBUG    | axiestudio.services.settings.base:set_user_agent:313 - Setting user agent to axiestudio

Traceback (most recent call last):

  File "/app/.venv/bin/axiestudio", line 10, in <module>

    sys.exit(main())

             ^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/axiestudio_launcher.py", line 18, in main

    from axiestudio.__main__ import main as axiestudio_main

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/__main__.py", line 31, in <module>

    from axiestudio.main import setup_app

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/main.py", line 26, in <module>

    from axiestudio.api import health_check_router, log_router, router

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/__init__.py", line 3, in <module>

    from axiestudio.api.router import router

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/router.py", line 4, in <module>

    from axiestudio.api.v1 import (

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/v1/__init__.py", line 4, in <module>

    from axiestudio.api.v1.email_verification import router as email_verification_router

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/v1/email_verification.py", line 8, in <module>

    from axiestudio.services.email.service import email_service

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/services/email/service.py", line 15, in <module>

    from axiestudio.services.settings.email import EmailSettings

ModuleNotFoundError: No module named 'axiestudio.services.settings.email'

2025-08-22 17:05:39.042 | DEBUG    | axiestudio.services.settings.base:set_database_url:361 - No database_url provided, trying AXIESTUDIO_DATABASE_URL env variable

2025-08-22 17:05:39.042 | DEBUG    | axiestudio.services.settings.base:set_database_url:364 - Using AXIESTUDIO_DATABASE_URL env variable.

2025-08-22 17:05:39.042 | DEBUG    | axiestudio.services.settings.base:set_components_path:460 - Setting default components path to components_path

2025-08-22 17:05:39.043 | DEBUG    | axiestudio.services.settings.base:set_components_path:468 - Components path: ['/app/.venv/lib/python3.12/site-packages/axiestudio/components']

2025-08-22 17:05:39.043 | DEBUG    | axiestudio.services.settings.base:set_user_agent:313 - Setting user agent to axiestudio

Traceback (most recent call last):

  File "/app/.venv/bin/axiestudio", line 10, in <module>

    sys.exit(main())

             ^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/axiestudio_launcher.py", line 18, in main

    from axiestudio.__main__ import main as axiestudio_main

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/__main__.py", line 31, in <module>

    from axiestudio.main import setup_app

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/main.py", line 26, in <module>

    from axiestudio.api import health_check_router, log_router, router

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/__init__.py", line 3, in <module>

    from axiestudio.api.router import router

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/router.py", line 4, in <module>

    from axiestudio.api.v1 import (

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/v1/__init__.py", line 4, in <module>

    from axiestudio.api.v1.email_verification import router as email_verification_router

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/v1/email_verification.py", line 8, in <module>

    from axiestudio.services.email.service import email_service

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/services/email/service.py", line 15, in <module>

    from axiestudio.services.settings.email import EmailSettings

ModuleNotFoundError: No module named 'axiestudio.services.settings.email'

2025-08-22 17:05:46.473 | DEBUG    | axiestudio.services.settings.base:set_database_url:361 - No database_url provided, trying AXIESTUDIO_DATABASE_URL env variable

2025-08-22 17:05:46.473 | DEBUG    | axiestudio.services.settings.base:set_database_url:364 - Using AXIESTUDIO_DATABASE_URL env variable.

2025-08-22 17:05:46.473 | DEBUG    | axiestudio.services.settings.base:set_components_path:460 - Setting default components path to components_path

2025-08-22 17:05:46.473 | DEBUG    | axiestudio.services.settings.base:set_components_path:468 - Components path: ['/app/.venv/lib/python3.12/site-packages/axiestudio/components']

2025-08-22 17:05:46.473 | DEBUG    | axiestudio.services.settings.base:set_user_agent:313 - Setting user agent to axiestudio

Traceback (most recent call last):

  File "/app/.venv/bin/axiestudio", line 10, in <module>

    sys.exit(main())

             ^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/axiestudio_launcher.py", line 18, in main

    from axiestudio.__main__ import main as axiestudio_main

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/__main__.py", line 31, in <module>

    from axiestudio.main import setup_app

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/main.py", line 26, in <module>

    from axiestudio.api import health_check_router, log_router, router

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/__init__.py", line 3, in <module>

    from axiestudio.api.router import router

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/router.py", line 4, in <module>

    from axiestudio.api.v1 import (

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/v1/__init__.py", line 4, in <module>

    from axiestudio.api.v1.email_verification import router as email_verification_router

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/v1/email_verification.py", line 8, in <module>

    from axiestudio.services.email.service import email_service

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/services/email/service.py", line 15, in <module>

    from axiestudio.services.settings.email import EmailSettings

ModuleNotFoundError: No module named 'axiestudio.services.settings.email'

2025-08-22 17:05:54.414 | DEBUG    | axiestudio.services.settings.base:set_database_url:361 - No database_url provided, trying AXIESTUDIO_DATABASE_URL env variable

2025-08-22 17:05:54.414 | DEBUG    | axiestudio.services.settings.base:set_database_url:364 - Using AXIESTUDIO_DATABASE_URL env variable.

2025-08-22 17:05:54.414 | DEBUG    | axiestudio.services.settings.base:set_components_path:460 - Setting default components path to components_path

2025-08-22 17:05:54.415 | DEBUG    | axiestudio.services.settings.base:set_components_path:468 - Components path: ['/app/.venv/lib/python3.12/site-packages/axiestudio/components']

2025-08-22 17:05:54.415 | DEBUG    | axiestudio.services.settings.base:set_user_agent:313 - Setting user agent to axiestudio

Traceback (most recent call last):

  File "/app/.venv/bin/axiestudio", line 10, in <module>

    sys.exit(main())

             ^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/axiestudio_launcher.py", line 18, in main

    from axiestudio.__main__ import main as axiestudio_main

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/__main__.py", line 31, in <module>

    from axiestudio.main import setup_app

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/main.py", line 26, in <module>

    from axiestudio.api import health_check_router, log_router, router

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/__init__.py", line 3, in <module>

    from axiestudio.api.router import router

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/router.py", line 4, in <module>

    from axiestudio.api.v1 import (

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/v1/__init__.py", line 4, in <module>

    from axiestudio.api.v1.email_verification import router as email_verification_router

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/v1/email_verification.py", line 8, in <module>

    from axiestudio.services.email.service import email_service

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/services/email/service.py", line 15, in <module>

    from axiestudio.services.settings.email import EmailSettings

ModuleNotFoundError: No module named 'axiestudio.services.settings.email'

2025-08-22 17:06:02.784 | DEBUG    | axiestudio.services.settings.base:set_database_url:361 - No database_url provided, trying AXIESTUDIO_DATABASE_URL env variable

2025-08-22 17:06:02.784 | DEBUG    | axiestudio.services.settings.base:set_database_url:364 - Using AXIESTUDIO_DATABASE_URL env variable.

2025-08-22 17:06:02.784 | DEBUG    | axiestudio.services.settings.base:set_components_path:460 - Setting default components path to components_path

2025-08-22 17:06:02.784 | DEBUG    | axiestudio.services.settings.base:set_components_path:468 - Components path: ['/app/.venv/lib/python3.12/site-packages/axiestudio/components']

2025-08-22 17:06:02.784 | DEBUG    | axiestudio.services.settings.base:set_user_agent:313 - Setting user agent to axiestudio

Traceback (most recent call last):

  File "/app/.venv/bin/axiestudio", line 10, in <module>

    sys.exit(main())

             ^^^^^^


  File "/app/.venv/lib/python3.12/site-packages/axiestudio/axiestudio_launcher.py", line 18, in main

    from axiestudio.__main__ import main as axiestudio_main

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/__main__.py", line 31, in <module>

    from axiestudio.main import setup_app

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/main.py", line 26, in <module>

    from axiestudio.api import health_check_router, log_router, router

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/__init__.py", line 3, in <module>

    from axiestudio.api.router import router

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/router.py", line 4, in <module>

    from axiestudio.api.v1 import (

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/v1/__init__.py", line 4, in <module>

    from axiestudio.api.v1.email_verification import router as email_verification_router

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/v1/email_verification.py", line 8, in <module>

    from axiestudio.services.email.service import email_service

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/services/email/service.py", line 15, in <module>

    from axiestudio.services.settings.email import EmailSettings

ModuleNotFoundError: No module named 'axiestudio.services.settings.email'

2025-08-22 17:06:10.606 | DEBUG    | axiestudio.services.settings.base:set_database_url:361 - No database_url provided, trying AXIESTUDIO_DATABASE_URL env variable

2025-08-22 17:06:10.606 | DEBUG    | axiestudio.services.settings.base:set_database_url:364 - Using AXIESTUDIO_DATABASE_URL env variable.

2025-08-22 17:06:10.606 | DEBUG    | axiestudio.services.settings.base:set_components_path:460 - Setting default components path to components_path

2025-08-22 17:06:10.606 | DEBUG    | axiestudio.services.settings.base:set_components_path:468 - Components path: ['/app/.venv/lib/python3.12/site-packages/axiestudio/components']

2025-08-22 17:06:10.606 | DEBUG    | axiestudio.services.settings.base:set_user_agent:313 - Setting user agent to axiestudio

Traceback (most recent call last):

  File "/app/.venv/bin/axiestudio", line 10, in <module>

    sys.exit(main())

             ^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/axiestudio_launcher.py", line 18, in main

    from axiestudio.__main__ import main as axiestudio_main

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/__main__.py", line 31, in <module>

    from axiestudio.main import setup_app

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/main.py", line 26, in <module>

    from axiestudio.api import health_check_router, log_router, router

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/__init__.py", line 3, in <module>

    from axiestudio.api.router import router

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/router.py", line 4, in <module>

    from axiestudio.api.v1 import (

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/v1/__init__.py", line 4, in <module>

    from axiestudio.api.v1.email_verification import router as email_verification_router

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/v1/email_verification.py", line 8, in <module>

    from axiestudio.services.email.service import email_service

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/services/email/service.py", line 15, in <module>

    from axiestudio.services.settings.email import EmailSettings

ModuleNotFoundError: No module named 'axiestudio.services.settings.email'

2025-08-22 17:06:18.298 | DEBUG    | axiestudio.services.settings.base:set_database_url:361 - No database_url provided, trying AXIESTUDIO_DATABASE_URL env variable

2025-08-22 17:06:18.298 | DEBUG    | axiestudio.services.settings.base:set_database_url:364 - Using AXIESTUDIO_DATABASE_URL env variable.

2025-08-22 17:06:18.298 | DEBUG    | axiestudio.services.settings.base:set_components_path:460 - Setting default components path to components_path

2025-08-22 17:06:18.298 | DEBUG    | axiestudio.services.settings.base:set_components_path:468 - Components path: ['/app/.venv/lib/python3.12/site-packages/axiestudio/components']

2025-08-22 17:06:18.298 | DEBUG    | axiestudio.services.settings.base:set_user_agent:313 - Setting user agent to axiestudio

Traceback (most recent call last):

  File "/app/.venv/bin/axiestudio", line 10, in <module>

    sys.exit(main())

             ^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/axiestudio_launcher.py", line 18, in main

    from axiestudio.__main__ import main as axiestudio_main

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/__main__.py", line 31, in <module>

    from axiestudio.main import setup_app

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/main.py", line 26, in <module>

    from axiestudio.api import health_check_router, log_router, router

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/__init__.py", line 3, in <module>

    from axiestudio.api.router import router

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/router.py", line 4, in <module>

    from axiestudio.api.v1 import (

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/v1/__init__.py", line 4, in <module>

    from axiestudio.api.v1.email_verification import router as email_verification_router

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/v1/email_verification.py", line 8, in <module>

    from axiestudio.services.email.service import email_service

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/services/email/service.py", line 15, in <module>

    from axiestudio.services.settings.email import EmailSettings

ModuleNotFoundError: No module named 'axiestudio.services.settings.email'

2025-08-22 17:06:26.659 | DEBUG    | axiestudio.services.settings.base:set_database_url:361 - No database_url provided, trying AXIESTUDIO_DATABASE_URL env variable

2025-08-22 17:06:26.659 | DEBUG    | axiestudio.services.settings.base:set_database_url:364 - Using AXIESTUDIO_DATABASE_URL env variable.

2025-08-22 17:06:26.659 | DEBUG    | axiestudio.services.settings.base:set_components_path:460 - Setting default components path to components_path

2025-08-22 17:06:26.659 | DEBUG    | axiestudio.services.settings.base:set_components_path:468 - Components path: ['/app/.venv/lib/python3.12/site-packages/axiestudio/components']

2025-08-22 17:06:26.659 | DEBUG    | axiestudio.services.settings.base:set_user_agent:313 - Setting user agent to axiestudio

Traceback (most recent call last):

  File "/app/.venv/bin/axiestudio", line 10, in <module>

    sys.exit(main())

             ^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/axiestudio_launcher.py", line 18, in main

    from axiestudio.__main__ import main as axiestudio_main

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/__main__.py", line 31, in <module>

    from axiestudio.main import setup_app

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/main.py", line 26, in <module>

    from axiestudio.api import health_check_router, log_router, router

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/__init__.py", line 3, in <module>

    from axiestudio.api.router import router

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/router.py", line 4, in <module>

    from axiestudio.api.v1 import (

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/v1/__init__.py", line 4, in <module>

    from axiestudio.api.v1.email_verification import router as email_verification_router

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/v1/email_verification.py", line 8, in <module>

    from axiestudio.services.email.service import email_service

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/services/email/service.py", line 15, in <module>

    from axiestudio.services.settings.email import EmailSettings

ModuleNotFoundError: No module named 'axiestudio.services.settings.email'

2025-08-22 17:06:36.520 | DEBUG    | axiestudio.services.settings.base:set_database_url:361 - No database_url provided, trying AXIESTUDIO_DATABASE_URL env variable

2025-08-22 17:06:36.520 | DEBUG    | axiestudio.services.settings.base:set_database_url:364 - Using AXIESTUDIO_DATABASE_URL env variable.

2025-08-22 17:06:36.520 | DEBUG    | axiestudio.services.settings.base:set_components_path:460 - Setting default components path to components_path

2025-08-22 17:06:36.520 | DEBUG    | axiestudio.services.settings.base:set_components_path:468 - Components path: ['/app/.venv/lib/python3.12/site-packages/axiestudio/components']

2025-08-22 17:06:36.521 | DEBUG    | axiestudio.services.settings.base:set_user_agent:313 - Setting user agent to axiestudio

Traceback (most recent call last):

  File "/app/.venv/bin/axiestudio", line 10, in <module>

    sys.exit(main())

             ^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/axiestudio_launcher.py", line 18, in main

    from axiestudio.__main__ import main as axiestudio_main

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/__main__.py", line 31, in <module>

    from axiestudio.main import setup_app

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/main.py", line 26, in <module>

    from axiestudio.api import health_check_router, log_router, router

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/__init__.py", line 3, in <module>

    from axiestudio.api.router import router

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/router.py", line 4, in <module>

    from axiestudio.api.v1 import (

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/v1/__init__.py", line 4, in <module>

    from axiestudio.api.v1.email_verification import router as email_verification_router

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/v1/email_verification.py", line 8, in <module>

    from axiestudio.services.email.service import email_service

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/services/email/service.py", line 15, in <module>

    from axiestudio.services.settings.email import EmailSettings

ModuleNotFoundError: No module named 'axiestudio.services.settings.email'

2025-08-22 17:06:45.226 | DEBUG    | axiestudio.services.settings.base:set_database_url:361 - No database_url provided, trying AXIESTUDIO_DATABASE_URL env variable

2025-08-22 17:06:45.226 | DEBUG    | axiestudio.services.settings.base:set_database_url:364 - Using AXIESTUDIO_DATABASE_URL env variable.

2025-08-22 17:06:45.226 | DEBUG    | axiestudio.services.settings.base:set_components_path:460 - Setting default components path to components_path

2025-08-22 17:06:45.226 | DEBUG    | axiestudio.services.settings.base:set_components_path:468 - Components path: ['/app/.venv/lib/python3.12/site-packages/axiestudio/components']

2025-08-22 17:06:45.226 | DEBUG    | axiestudio.services.settings.base:set_user_agent:313 - Setting user agent to axiestudio

Traceback (most recent call last):

  File "/app/.venv/bin/axiestudio", line 10, in <module>

    sys.exit(main())

             ^^^^^^

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/axiestudio_launcher.py", line 18, in main

    from axiestudio.__main__ import main as axiestudio_main

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/__main__.py", line 31, in <module>

    from axiestudio.main import setup_app

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/main.py", line 26, in <module>

    from axiestudio.api import health_check_router, log_router, router

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/__init__.py", line 3, in <module>

    from axiestudio.api.router import router

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/router.py", line 4, in <module>

    from axiestudio.api.v1 import (

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/v1/__init__.py", line 4, in <module>

    from axiestudio.api.v1.email_verification import router as email_verification_router

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/api/v1/email_verification.py", line 8, in <module>

    from axiestudio.services.email.service import email_service

  File "/app/.venv/lib/python3.12/site-packages/axiestudio/services/email/service.py", line 15, in <module>

    from axiestudio.services.settings.email import EmailSettings

ModuleNotFoundError: No module named 'axiestudio.services.settings.email'